import { useQuery } from '@apollo/client';
import Head from 'next/head'
import { useRouter } from 'next/router';
import React from 'react'
import Post from '../../components/Post';
import { GET_POST_BY_ID } from '../../graphql/queries';

const PostDetails = () => {
    const router = useRouter();
    const { postId } = router.query;
    const { data } = useQuery(GET_POST_BY_ID,{
        variables:{
            id:postId
        }
    });

    console.log(data)

  return (
    <main className="max-w-7xl mx-auto">
        <Head>
            <title>Post Details</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className='ml-[220px] pt-20 relative text-gray-400'>
           
        </div>

    </main>
  )
}

export default PostDetails