import Head from 'next/head';
import { useRouter } from 'next/router';
import React, { useEffect, useState } from 'react'
import CreatePost from '../../components/CreatePost';
import HomeFeed from '../../components/HomeFeed';

const SubtalkzDetails = () => {
  const router = useRouter();
  
  const { topic } = router.query;
  const [topicImage,setTopicImage] = useState<string>("");

  useEffect(()=>{
    const getRandomImage = async() =>{
      const data = await fetch(`https://source.unsplash.com/800x800/?${topic}`);
      console.log(data)
      setTopicImage(data.url)
    }

    getRandomImage();
  },[topic]);

  return (

    <main className="max-w-7xl mx-auto">
      <Head>
          <title>Subtalkz | {topic}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=' max-w-3xl mx-auto pt-8 px-4 lg:pt-20 relative text-gray-400'>
        <div className="bg-[#0EA5E9] w-full h-36 relative">
          <div className="absolute -bottom-[75px] left-5 ">
            <img src={topicImage || "https://i.pinimg.com/564x/a5/f6/47/a5f647e37b2573fc3d564ed0be08d500.jpg"} className="w-[150px] h-[150px] rounded-full object-cover border-4" />

          </div>
        </div>
        <div className="relative pt-20">
          <p className='font-bold text-xl text-white'>Welcome to the t/{topic} subtalkz</p>
          <p>t/{topic}</p>
          
          <CreatePost topic={topic as string} />
          
          <HomeFeed topic={topic as string} />
          
        </div>
      </div>
    </main>

  )
}

export default SubtalkzDetails