import { useQuery } from "@apollo/client";
import Head from "next/head";
import { useRouter } from "next/router";
import Post from "../../components/Post";
import { SEARCH_POSTS } from "../../graphql/queries";
import { IPost } from "../../interface";

const ExplorePage = () => {
  const router = useRouter();
  const { q } = router.query;
  const { data: posts } = useQuery(SEARCH_POSTS, {
    variables: {
      q:`%${q}%`,
    },
  });

  console.log(posts);
  return (
    <div className="max-w-7xl mx-auto">
      <Head>
        <title>Explore</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="relative pt-4 lg:pt-24 max-w-[642px] mx-auto px-4 lg:px-0">
        <div className="flex flex-col gap-y-4">
          {posts?.getTalkZ_postListBySearch?.map((post: IPost,i:number) => (
            <Post post={post} key={i} />
          ))}
        </div>
      </div>
    </div>
  );
};

export default ExplorePage;
